name: Continuous Integration (CI)
#Run CI jobs on all branches by default
on:
  push:
  pull_request:

jobs:
  test:
    name:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out the Git repository
        uses: actions/checkout@v4
      - name: Set up Java toolchain
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"
          cache: "gradle"
      - name: Set up permissions for Gradle
        run: chmod +x ./gradlew
      - name: Run unit tests
        run: ./gradlew test